/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as operations from "../operations/index.js";
import { SafepayError } from "./safepayerror.js";

/**
 * 404
 */
export type DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundErrorData =
  {
    error?: string | undefined;
  };

/**
 * 404
 */
export class DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError
  extends SafepayError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundErrorData;

  constructor(
    err:
      DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name =
      "DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError";
  }
}

/**
 * 401
 */
export type DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedErrorData =
  {
    data?: any | null | undefined;
    status?:
      | operations.DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdStatus
      | undefined;
  };

/**
 * 401
 */
export class DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError
  extends SafepayError
{
  data?: any | null | undefined;
  status?:
    | operations.DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdStatus
    | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedErrorData;

  constructor(
    err:
      DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.data != null) this.data = err.data;
    if (err.status != null) this.status = err.status;

    this.name =
      "DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError";
  }
}

/** @internal */
export const DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError$inboundSchema:
  z.ZodType<
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError$Outbound =
  {
    error?: string | undefined;
  };

/** @internal */
export const DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError$outboundSchema:
  z.ZodType<
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError$Outbound,
    z.ZodTypeDef,
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError
  > = z.instanceof(
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError$ {
  /** @deprecated use `DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError$inboundSchema` instead. */
  export const inboundSchema =
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError$inboundSchema;
  /** @deprecated use `DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError$outboundSchema` instead. */
  export const outboundSchema =
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError$outboundSchema;
  /** @deprecated use `DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError$Outbound` instead. */
  export type Outbound =
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError$Outbound;
}

/** @internal */
export const DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError$inboundSchema:
  z.ZodType<
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.nullable(z.any()).optional(),
    status: z.lazy(() =>
      operations
        .DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdStatus$inboundSchema
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError$Outbound =
  {
    data?: any | null | undefined;
    status?:
      | operations.DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdStatus$Outbound
      | undefined;
  };

/** @internal */
export const DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError$outboundSchema:
  z.ZodType<
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError$Outbound,
    z.ZodTypeDef,
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError
  > = z.instanceof(
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      data: z.nullable(z.any()).optional(),
      status: z.lazy(() =>
        operations
          .DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdStatus$outboundSchema
      ).optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError$ {
  /** @deprecated use `DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError$inboundSchema;
  /** @deprecated use `DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError$outboundSchema;
  /** @deprecated use `DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError$Outbound` instead. */
  export type Outbound =
    DeleteClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError$Outbound;
}
