/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as operations from "../operations/index.js";
import { SafepayError } from "./safepayerror.js";

/**
 * 404
 */
export type GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundErrorData =
  {
    error?: string | undefined;
  };

/**
 * 404
 */
export class GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError
  extends SafepayError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundErrorData;

  constructor(
    err:
      GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name =
      "GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError";
  }
}

/**
 * 401
 */
export type GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedErrorData =
  {
    data?: any | null | undefined;
    status?:
      | operations.GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541Status
      | undefined;
  };

/**
 * 401
 */
export class GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError
  extends SafepayError
{
  data?: any | null | undefined;
  status?:
    | operations.GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541Status
    | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedErrorData;

  constructor(
    err:
      GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.data != null) this.data = err.data;
    if (err.status != null) this.status = err.status;

    this.name =
      "GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError";
  }
}

/** @internal */
export const GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError$inboundSchema:
  z.ZodType<
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError$Outbound =
  {
    error?: string | undefined;
  };

/** @internal */
export const GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError$outboundSchema:
  z.ZodType<
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError$Outbound,
    z.ZodTypeDef,
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError
  > = z.instanceof(
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError$ {
  /** @deprecated use `GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError$inboundSchema` instead. */
  export const inboundSchema =
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError$inboundSchema;
  /** @deprecated use `GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError$outboundSchema` instead. */
  export const outboundSchema =
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError$outboundSchema;
  /** @deprecated use `GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError$Outbound` instead. */
  export type Outbound =
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541NotFoundError$Outbound;
}

/** @internal */
export const GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError$inboundSchema:
  z.ZodType<
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.nullable(z.any()).optional(),
    status: z.lazy(() =>
      operations
        .GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541Status$inboundSchema
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError$Outbound =
  {
    data?: any | null | undefined;
    status?:
      | operations.GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541Status$Outbound
      | undefined;
  };

/** @internal */
export const GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError$outboundSchema:
  z.ZodType<
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError$Outbound,
    z.ZodTypeDef,
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError
  > = z.instanceof(
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      data: z.nullable(z.any()).optional(),
      status: z.lazy(() =>
        operations
          .GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541Status$outboundSchema
      ).optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError$ {
  /** @deprecated use `GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError$inboundSchema;
  /** @deprecated use `GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError$outboundSchema;
  /** @deprecated use `GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError$Outbound` instead. */
  export type Outbound =
    GetClientSubscriptionsV1SubC841ea40613c41a389847cb11f66d541UnauthorizedError$Outbound;
}
