/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as operations from "../operations/index.js";
import { SafepayError } from "./safepayerror.js";

/**
 * 404
 */
export type GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundErrorData =
  {
    error?: string | undefined;
  };

/**
 * 404
 */
export class GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError
  extends SafepayError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundErrorData;

  constructor(
    err:
      GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name =
      "GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError";
  }
}

/**
 * 401
 */
export type GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedErrorData =
  {
    data?: any | null | undefined;
    status?:
      | operations.GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1Status
      | undefined;
  };

/**
 * 401
 */
export class GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError
  extends SafepayError
{
  data?: any | null | undefined;
  status?:
    | operations.GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1Status
    | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedErrorData;

  constructor(
    err:
      GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.data != null) this.data = err.data;
    if (err.status != null) this.status = err.status;

    this.name =
      "GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError";
  }
}

/** @internal */
export const GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError$inboundSchema:
  z.ZodType<
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError$Outbound =
  {
    error?: string | undefined;
  };

/** @internal */
export const GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError$outboundSchema:
  z.ZodType<
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError$Outbound,
    z.ZodTypeDef,
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError
  > = z.instanceof(
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError$ {
  /** @deprecated use `GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError$inboundSchema` instead. */
  export const inboundSchema =
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError$inboundSchema;
  /** @deprecated use `GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError$outboundSchema` instead. */
  export const outboundSchema =
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError$outboundSchema;
  /** @deprecated use `GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError$Outbound` instead. */
  export type Outbound =
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1NotFoundError$Outbound;
}

/** @internal */
export const GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError$inboundSchema:
  z.ZodType<
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.nullable(z.any()).optional(),
    status: z.lazy(() =>
      operations
        .GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1Status$inboundSchema
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError$Outbound =
  {
    data?: any | null | undefined;
    status?:
      | operations.GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1Status$Outbound
      | undefined;
  };

/** @internal */
export const GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError$outboundSchema:
  z.ZodType<
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError$Outbound,
    z.ZodTypeDef,
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError
  > = z.instanceof(
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      data: z.nullable(z.any()).optional(),
      status: z.lazy(() =>
        operations
          .GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1Status$outboundSchema
      ).optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError$ {
  /** @deprecated use `GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError$inboundSchema;
  /** @deprecated use `GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError$outboundSchema;
  /** @deprecated use `GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError$Outbound` instead. */
  export type Outbound =
    GetClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1UnauthorizedError$Outbound;
}
