/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as operations from "../operations/index.js";
import { SafepayError } from "./safepayerror.js";

/**
 * 401
 */
export type GetClientSubscriptionsV1SearchUnauthorizedErrorData = {
  data?: any | null | undefined;
  status?: operations.GetClientSubscriptionsV1SearchStatus | undefined;
};

/**
 * 401
 */
export class GetClientSubscriptionsV1SearchUnauthorizedError
  extends SafepayError
{
  data?: any | null | undefined;
  status?: operations.GetClientSubscriptionsV1SearchStatus | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetClientSubscriptionsV1SearchUnauthorizedErrorData;

  constructor(
    err: GetClientSubscriptionsV1SearchUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.data != null) this.data = err.data;
    if (err.status != null) this.status = err.status;

    this.name = "GetClientSubscriptionsV1SearchUnauthorizedError";
  }
}

/** @internal */
export const GetClientSubscriptionsV1SearchUnauthorizedError$inboundSchema:
  z.ZodType<
    GetClientSubscriptionsV1SearchUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.nullable(z.any()).optional(),
    status: z.lazy(() =>
      operations.GetClientSubscriptionsV1SearchStatus$inboundSchema
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetClientSubscriptionsV1SearchUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type GetClientSubscriptionsV1SearchUnauthorizedError$Outbound = {
  data?: any | null | undefined;
  status?: operations.GetClientSubscriptionsV1SearchStatus$Outbound | undefined;
};

/** @internal */
export const GetClientSubscriptionsV1SearchUnauthorizedError$outboundSchema:
  z.ZodType<
    GetClientSubscriptionsV1SearchUnauthorizedError$Outbound,
    z.ZodTypeDef,
    GetClientSubscriptionsV1SearchUnauthorizedError
  > = z.instanceof(GetClientSubscriptionsV1SearchUnauthorizedError)
    .transform(v => v.data$)
    .pipe(z.object({
      data: z.nullable(z.any()).optional(),
      status: z.lazy(() =>
        operations.GetClientSubscriptionsV1SearchStatus$outboundSchema
      ).optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetClientSubscriptionsV1SearchUnauthorizedError$ {
  /** @deprecated use `GetClientSubscriptionsV1SearchUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    GetClientSubscriptionsV1SearchUnauthorizedError$inboundSchema;
  /** @deprecated use `GetClientSubscriptionsV1SearchUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    GetClientSubscriptionsV1SearchUnauthorizedError$outboundSchema;
  /** @deprecated use `GetClientSubscriptionsV1SearchUnauthorizedError$Outbound` instead. */
  export type Outbound =
    GetClientSubscriptionsV1SearchUnauthorizedError$Outbound;
}
