/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as operations from "../operations/index.js";
import { SafepayError } from "./safepayerror.js";

/**
 * 401
 */
export type GetUserWalletsV1UnauthorizedErrorData = {
  data?: any | null | undefined;
  status?: operations.GetUserWalletsV1Status | undefined;
};

/**
 * 401
 */
export class GetUserWalletsV1UnauthorizedError extends SafepayError {
  data?: any | null | undefined;
  status?: operations.GetUserWalletsV1Status | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetUserWalletsV1UnauthorizedErrorData;

  constructor(
    err: GetUserWalletsV1UnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.data != null) this.data = err.data;
    if (err.status != null) this.status = err.status;

    this.name = "GetUserWalletsV1UnauthorizedError";
  }
}

/** @internal */
export const GetUserWalletsV1UnauthorizedError$inboundSchema: z.ZodType<
  GetUserWalletsV1UnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.nullable(z.any()).optional(),
  status: z.lazy(() => operations.GetUserWalletsV1Status$inboundSchema)
    .optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetUserWalletsV1UnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetUserWalletsV1UnauthorizedError$Outbound = {
  data?: any | null | undefined;
  status?: operations.GetUserWalletsV1Status$Outbound | undefined;
};

/** @internal */
export const GetUserWalletsV1UnauthorizedError$outboundSchema: z.ZodType<
  GetUserWalletsV1UnauthorizedError$Outbound,
  z.ZodTypeDef,
  GetUserWalletsV1UnauthorizedError
> = z.instanceof(GetUserWalletsV1UnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    data: z.nullable(z.any()).optional(),
    status: z.lazy(() => operations.GetUserWalletsV1Status$outboundSchema)
      .optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserWalletsV1UnauthorizedError$ {
  /** @deprecated use `GetUserWalletsV1UnauthorizedError$inboundSchema` instead. */
  export const inboundSchema = GetUserWalletsV1UnauthorizedError$inboundSchema;
  /** @deprecated use `GetUserWalletsV1UnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    GetUserWalletsV1UnauthorizedError$outboundSchema;
  /** @deprecated use `GetUserWalletsV1UnauthorizedError$Outbound` instead. */
  export type Outbound = GetUserWalletsV1UnauthorizedError$Outbound;
}
