/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as operations from "../operations/index.js";
import { SafepayError } from "./safepayerror.js";

/**
 * 401
 */
export type PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedErrorData =
  {
    data?: any | null | undefined;
    status?:
      | operations.PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedStatus
      | undefined;
  };

/**
 * 401
 */
export class PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError
  extends SafepayError
{
  data?: any | null | undefined;
  status?:
    | operations.PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedStatus
    | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedErrorData;

  constructor(
    err:
      PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.data != null) this.data = err.data;
    if (err.status != null) this.status = err.status;

    this.name =
      "PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError";
  }
}

/**
 * 400
 */
export type PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestErrorData =
  {
    data?: any | null | undefined;
    status?:
      | operations.PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestStatus
      | undefined;
  };

/**
 * 400
 */
export class PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError
  extends SafepayError
{
  data?: any | null | undefined;
  status?:
    | operations.PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestStatus
    | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestErrorData;

  constructor(
    err:
      PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.data != null) this.data = err.data;
    if (err.status != null) this.status = err.status;

    this.name =
      "PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError";
  }
}

/** @internal */
export const PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.nullable(z.any()).optional(),
    status: z.lazy(() =>
      operations
        .PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedStatus$inboundSchema
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError$Outbound =
  {
    data?: any | null | undefined;
    status?:
      | operations.PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedStatus$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError
  > = z.instanceof(
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      data: z.nullable(z.any()).optional(),
      status: z.lazy(() =>
        operations
          .PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedStatus$outboundSchema
      ).optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError$ {
  /** @deprecated use `PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalUnauthorizedError$Outbound;
}

/** @internal */
export const PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.nullable(z.any()).optional(),
    status: z.lazy(() =>
      operations
        .PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestStatus$inboundSchema
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError$Outbound =
  {
    data?: any | null | undefined;
    status?:
      | operations.PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestStatus$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError
  > = z.instanceof(
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      data: z.nullable(z.any()).optional(),
      status: z.lazy(() =>
        operations
          .PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestStatus$outboundSchema
      ).optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError$ {
  /** @deprecated use `PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalBadRequestError$Outbound;
}
