/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as operations from "../operations/index.js";
import { SafepayError } from "./safepayerror.js";

/**
 * 404
 */
export type PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundErrorData =
  {
    error?: string | undefined;
  };

/**
 * 404
 */
export class PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError
  extends SafepayError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundErrorData;

  constructor(
    err:
      PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name =
      "PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError";
  }
}

/**
 * 401
 */
export type PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedErrorData =
  {
    data?: any | null | undefined;
    status?:
      | operations.PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3Status
      | undefined;
  };

/**
 * 401
 */
export class PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError
  extends SafepayError
{
  data?: any | null | undefined;
  status?:
    | operations.PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3Status
    | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedErrorData;

  constructor(
    err:
      PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.data != null) this.data = err.data;
    if (err.status != null) this.status = err.status;

    this.name =
      "PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError";
  }
}

/** @internal */
export const PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError$inboundSchema:
  z.ZodType<
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError$Outbound =
  {
    error?: string | undefined;
  };

/** @internal */
export const PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError$outboundSchema:
  z.ZodType<
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError$Outbound,
    z.ZodTypeDef,
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError
  > = z.instanceof(
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError$ {
  /** @deprecated use `PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError$inboundSchema` instead. */
  export const inboundSchema =
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError$inboundSchema;
  /** @deprecated use `PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError$outboundSchema` instead. */
  export const outboundSchema =
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError$outboundSchema;
  /** @deprecated use `PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError$Outbound` instead. */
  export type Outbound =
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3NotFoundError$Outbound;
}

/** @internal */
export const PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError$inboundSchema:
  z.ZodType<
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.nullable(z.any()).optional(),
    status: z.lazy(() =>
      operations
        .PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3Status$inboundSchema
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError$Outbound =
  {
    data?: any | null | undefined;
    status?:
      | operations.PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3Status$Outbound
      | undefined;
  };

/** @internal */
export const PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError$outboundSchema:
  z.ZodType<
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError$Outbound,
    z.ZodTypeDef,
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError
  > = z.instanceof(
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      data: z.nullable(z.any()).optional(),
      status: z.lazy(() =>
        operations
          .PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3Status$outboundSchema
      ).optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError$ {
  /** @deprecated use `PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError$inboundSchema;
  /** @deprecated use `PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError$outboundSchema;
  /** @deprecated use `PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError$Outbound` instead. */
  export type Outbound =
    PutClientSubscriptionsV1SubEe09b0f9974f4deeB1b34ad8dad2e7b3UnauthorizedError$Outbound;
}
