/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authLogin } from "../../funcs/authLogin.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostAuthV2UserLoginRequest$inboundSchema,
};

export const tool$authLogin: ToolDefinition<typeof args> = {
  name: "auth-login",
  description: `Create Shopper JWT Using Password`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await authLogin(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
