/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetPaymentMethod } from "../../funcs/customersGetPaymentMethod.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$customersGetPaymentMethod: ToolDefinition = {
  name: "customers-get-payment-method",
  description: `Find Payment Method`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await customersGetPaymentMethod(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
