/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getClientSubscriptionsV1Search } from "../../funcs/getClientSubscriptionsV1Search.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetClientSubscriptionsV1SearchRequest$inboundSchema
    .optional(),
};

export const tool$getClientSubscriptionsV1Search: ToolDefinition<typeof args> =
  {
    name: "get-client-subscriptions-v1-search",
    description: `Search Subscriptions`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await getClientSubscriptionsV1Search(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value.result;

      return formatResult(value, apiCall);
    },
  };
