/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcd } from "../../funcs/getClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcd.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$getClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcd:
  ToolDefinition = {
    name: "get-client-plans-v1-plan-d4869a78-0036-4d66-97bd-6afeb5282bcd",
    description: `Find Plan`,
    tool: async (client, ctx) => {
      const [result, apiCall] =
        await getClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcd(
          client,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value.result;

      return formatResult(value, apiCall);
    },
  };
