/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getInvoiceQuickLinksV1 } from "../../funcs/getInvoiceQuickLinksV1.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetInvoiceQuickLinksV1Request$inboundSchema.optional(),
};

export const tool$getInvoiceQuickLinksV1: ToolDefinition<typeof args> = {
  name: "get-invoice-quick-links-v1",
  description: `Search Quick Links`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getInvoiceQuickLinksV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
