/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getUserV2Exists } from "../../funcs/getUserV2Exists.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetUserV2ExistsRequest$inboundSchema.optional(),
};

export const tool$getUserV2Exists: ToolDefinition<typeof args> = {
  name: "get-user-v2-exists",
  description: `Safepay Shopper Exists`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getUserV2Exists(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
