/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { linksGet } from "../../funcs/linksGet.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$linksGet: ToolDefinition = {
  name: "links-get",
  description: `Find`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await linksGet(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
