/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsReverse } from "../../funcs/paymentsReverse.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations
    .PostOrderPaymentsV3Track9d765b77608f46bc84d25f4392753ca3ReversalRequest$inboundSchema
    .optional(),
};

export const tool$paymentsReverse: ToolDefinition<typeof args> = {
  name: "payments-reverse",
  description: `Reverse`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await paymentsReverse(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
