/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsAddMetadata } from "../../funcs/paymentsAddMetadata.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations
    .PostOrderPaymentsV3TrackAa38d5b7A3a245c5Bed8586b0bae8d06MetadataRequest$inboundSchema
    .optional(),
};

export const tool$paymentsAddMetadata: ToolDefinition<typeof args> = {
  name: "payments-add-metadata",
  description: `Add Metadata`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await paymentsAddMetadata(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
