/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postClientHooksV2Test } from "../../funcs/postClientHooksV2Test.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostClientHooksV2TestRequest$inboundSchema.optional(),
};

export const tool$postClientHooksV2Test: ToolDefinition<typeof args> = {
  name: "post-client-hooks-v2-test",
  description: `Test Webhook`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await postClientHooksV2Test(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
