/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7 } from "../../funcs/postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations
    .PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$inboundSchema
    .optional(),
};

export const tool$postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7:
  ToolDefinition<typeof args> = {
    name: "post-order-payments-v3-track-1a46dc70-91f9-4892-8e25-0bb5205b69c7",
    description: `Capture`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value.result;

      return formatResult(value, apiCall);
    },
  };
