/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postOrderPaymentsV3Track7233ed61Fe5048368a84C5e17ae90f4d } from "../../funcs/postOrderPaymentsV3Track7233ed61Fe5048368a84C5e17ae90f4d.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations
    .PostOrderPaymentsV3Track7233ed61Fe5048368a84C5e17ae90f4dRequest$inboundSchema
    .optional(),
};

export const tool$postOrderPaymentsV3Track7233ed61Fe5048368a84C5e17ae90f4d:
  ToolDefinition<typeof args> = {
    name: "post-order-payments-v3-track-7233ed61-fe50-4836-8a84-c5e17ae90f4d",
    description: `Generate Capture Context`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await postOrderPaymentsV3Track7233ed61Fe5048368a84C5e17ae90f4d(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value.result;

      return formatResult(value, apiCall);
    },
  };
