/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postAuthV1CompanyAuthenticate } from "../../funcs/postAuthV1CompanyAuthenticate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostAuthV1CompanyAuthenticateRequest$inboundSchema
    .optional(),
};

export const tool$postAuthV1CompanyAuthenticate: ToolDefinition<typeof args> = {
  name: "post-auth-v1-company-authenticate",
  description: `Create Merchant JWT`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await postAuthV1CompanyAuthenticate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
