/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postOrderPaymentsV3TrackDccdef16008e4fae81cc1b7d81bf6c44 } from "../../funcs/postOrderPaymentsV3TrackDccdef16008e4fae81cc1b7d81bf6c44.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations
    .PostOrderPaymentsV3TrackDccdef16008e4fae81cc1b7d81bf6c44Request$inboundSchema
    .optional(),
};

export const tool$postOrderPaymentsV3TrackDccdef16008e4fae81cc1b7d81bf6c44:
  ToolDefinition<typeof args> = {
    name: "post-order-payments-v3-track-dccdef16-008e-4fae-81cc-1b7d81bf6c44",
    description: `Process Transient Token`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await postOrderPaymentsV3TrackDccdef16008e4fae81cc1b7d81bf6c44(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value.result;

      return formatResult(value, apiCall);
    },
  };
