/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1Refund } from "../../funcs/postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1Refund.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1Refund:
  ToolDefinition = {
    name:
      "post-client-transactions-v1-txn-17553398-b91d-41e9-ae47-165e194d06a1-refund",
    description: `Refund Transaction`,
    tool: async (client, ctx) => {
      const [result, apiCall] =
        await postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1Refund(
          client,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value.result;

      return formatResult(value, apiCall);
    },
  };
