/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postClientApiSettingsV1 } from "../../funcs/postClientApiSettingsV1.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$postClientApiSettingsV1: ToolDefinition = {
  name: "post-client-api-settings-v1",
  description: `Create API Key`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await postClientApiSettingsV1(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
