/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { quickLinksCreate } from "../../funcs/quickLinksCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostInvoiceQuickLinksV1Request$inboundSchema,
};

export const tool$quickLinksCreate: ToolDefinition<typeof args> = {
  name: "quick-links-create",
  description: `Create Quick Link`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await quickLinksCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
