/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { quickLinksUpdate } from "../../funcs/quickLinksUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations
    .PutInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cRequest$inboundSchema
    .optional(),
};

export const tool$quickLinksUpdate: ToolDefinition<typeof args> = {
  name: "quick-links-update",
  description: `Update Quick Link`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await quickLinksUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
