/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsSearch } from "../../funcs/subscriptionsSearch.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetClientSubscriptionsV1SearchRequest$inboundSchema
    .optional(),
};

export const tool$subscriptionsSearch: ToolDefinition<typeof args> = {
  name: "subscriptions-search",
  description: `Search Subscriptions`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subscriptionsSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
