/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersFindSafepayShopper } from "../../funcs/usersFindSafepayShopper.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$usersFindSafepayShopper: ToolDefinition = {
  name: "users-find-safepay-shopper",
  description: `Find Safepay Shopper`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await usersFindSafepayShopper(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
