/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SafepayCore } from "../core.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SafepayError } from "../models/errors/safepayerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Find Plan
 */
export function plansGet(
  client: SafepayCore,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.GetClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdResponse,
    | errors.GetClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError
    | errors.GetClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError
    | SafepayError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    options,
  ));
}

async function $do(
  client: SafepayCore,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.GetClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdResponse,
      | errors.GetClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError
      | errors.GetClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError
      | SafepayError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const path = pathToFunc(
    "/client/plans/v1/plan_d4869a78-0036-4d66-97bd-6afeb5282bcd",
  )();

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID:
      "get_/client/plans/v1/plan_d4869a78-0036-4d66-97bd-6afeb5282bcd",
    oAuth2Scopes: [],

    resolvedSecurity: null,

    securitySource: null,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    method: "GET",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["401", "404", "4XX", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.GetClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdResponse,
    | errors.GetClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError
    | errors.GetClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError
    | SafepayError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(
      200,
      operations
        .GetClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdResponse$inboundSchema,
      { hdrs: true, key: "Result" },
    ),
    M.jsonErr(
      401,
      errors
        .GetClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdUnauthorizedError$inboundSchema,
      { hdrs: true },
    ),
    M.jsonErr(
      404,
      errors
        .GetClientPlansV1PlanD4869a7800364d6697bd6afeb5282bcdNotFoundError$inboundSchema,
      { hdrs: true },
    ),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
