/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansCreate } from "../funcs/plansCreate.js";
import { plansSearch } from "../funcs/plansSearch.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Plans extends ClientSDK {
  /**
   * Create Plan
   */
  async create(
    request: operations.PostClientPlansV1Request,
    options?: RequestOptions,
  ): Promise<operations.PostClientPlansV1Response> {
    return unwrapAsync(plansCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Search Plans
   */
  async search(
    request?: operations.GetClientPlansV1SearchRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetClientPlansV1SearchResponse> {
    return unwrapAsync(plansSearch(
      this,
      request,
      options,
    ));
  }
}
