/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userAddressesFindById } from "../funcs/userAddressesFindById.js";
import { userAddressesUpdateById } from "../funcs/userAddressesUpdateById.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class UserAddresses extends ClientSDK {
  /**
   * Update Address
   */
  async updateById(
    request?:
      | operations.PutUserAddressV2Address5ce54f87A8234da689907b26d048ce00Request
      | undefined,
    options?: RequestOptions,
  ): Promise<
    operations.PutUserAddressV2Address5ce54f87A8234da689907b26d048ce00Response
  > {
    return unwrapAsync(userAddressesUpdateById(
      this,
      request,
      options,
    ));
  }

  /**
   * Find Address
   */
  async findById(
    options?: RequestOptions,
  ): Promise<
    operations.GetUserAddressV2Address5ce54f87A8234da689907b26d048ce00Response
  > {
    return unwrapAsync(userAddressesFindById(
      this,
      options,
    ));
  }
}
