/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userCustomersDeletePaymentMethod } from "../funcs/userCustomersDeletePaymentMethod.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class UserCustomers extends ClientSDK {
  /**
   * Delete Payment Method
   */
  async deletePaymentMethod(
    options?: RequestOptions,
  ): Promise<
    operations.DeleteUserCustomersV1Cus2fc20245E0f8447fAf75Fa651cfd54aaWalletPmBea0077422ba44ce82c53cdd1a342e89Response
  > {
    return unwrapAsync(userCustomersDeletePaymentMethod(
      this,
      options,
    ));
  }
}
