/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Example usage of the @dhaba/safepay-ts SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx postV1CompanyLogin.ts
 */

import { Safepay } from "@dhaba/safepay-ts";

const safepay = new Safepay();

async function main() {
  const result = await safepay.postV1CompanyLogin();

  console.log(result);
}

main().catch(console.error);
