/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus =
  {
    errors?: Array<string> | undefined;
    message?: string | undefined;
  };

export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus =
  {
    errors?: Array<string> | undefined;
    message?: string | undefined;
  };

export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus =
  {
    errors?: Array<string> | undefined;
    message?: string | undefined;
  };

export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data = {
  token?: string | undefined;
  deleted?: boolean | undefined;
};

export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status = {
  errors?: Array<any> | undefined;
  message?: string | undefined;
};

/**
 * 200
 */
export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody =
  {
    data?:
      | DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data
      | undefined;
    status?:
      | DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status
      | undefined;
  };

export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response = {
  headers: { [k: string]: Array<string> };
  result: DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody;
};

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$inboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(z.string()).optional(),
    message: z.string().optional(),
  });

/** @internal */
export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$Outbound =
  {
    errors?: Array<string> | undefined;
    message?: string | undefined;
  };

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$outboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$Outbound,
    z.ZodTypeDef,
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus
  > = z.object({
    errors: z.array(z.string()).optional(),
    message: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$ {
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$inboundSchema` instead. */
  export const inboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$inboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$outboundSchema` instead. */
  export const outboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$outboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$Outbound` instead. */
  export type Outbound =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$Outbound;
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatusToJSON(
  deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus:
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus,
): string {
  return JSON.stringify(
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$outboundSchema
      .parse(
        deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus,
      ),
  );
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatusFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52NotFoundStatus' from JSON`,
  );
}

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$inboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(z.string()).optional(),
    message: z.string().optional(),
  });

/** @internal */
export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$Outbound =
  {
    errors?: Array<string> | undefined;
    message?: string | undefined;
  };

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$outboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$Outbound,
    z.ZodTypeDef,
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus
  > = z.object({
    errors: z.array(z.string()).optional(),
    message: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$ {
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$inboundSchema` instead. */
  export const inboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$inboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$outboundSchema` instead. */
  export const outboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$outboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$Outbound` instead. */
  export type Outbound =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$Outbound;
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatusToJSON(
  deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus:
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus,
): string {
  return JSON.stringify(
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$outboundSchema
      .parse(
        deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus,
      ),
  );
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatusFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52UnauthorizedStatus' from JSON`,
  );
}

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$inboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(z.string()).optional(),
    message: z.string().optional(),
  });

/** @internal */
export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$Outbound =
  {
    errors?: Array<string> | undefined;
    message?: string | undefined;
  };

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$outboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$Outbound,
    z.ZodTypeDef,
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus
  > = z.object({
    errors: z.array(z.string()).optional(),
    message: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$ {
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$inboundSchema` instead. */
  export const inboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$inboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$outboundSchema` instead. */
  export const outboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$outboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$Outbound` instead. */
  export type Outbound =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$Outbound;
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatusToJSON(
  deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus:
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus,
): string {
  return JSON.stringify(
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$outboundSchema
      .parse(
        deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus,
      ),
  );
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatusFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52BadRequestStatus' from JSON`,
  );
}

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$inboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data,
    z.ZodTypeDef,
    unknown
  > = z.object({
    token: z.string().optional(),
    deleted: z.boolean().optional(),
  });

/** @internal */
export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$Outbound =
  {
    token?: string | undefined;
    deleted?: boolean | undefined;
  };

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$outboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$Outbound,
    z.ZodTypeDef,
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data
  > = z.object({
    token: z.string().optional(),
    deleted: z.boolean().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$ {
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$inboundSchema` instead. */
  export const inboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$inboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$outboundSchema` instead. */
  export const outboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$outboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$Outbound` instead. */
  export type Outbound =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$Outbound;
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52DataToJSON(
  deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data:
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data,
): string {
  return JSON.stringify(
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$outboundSchema
      .parse(deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data),
  );
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52DataFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data' from JSON`,
  );
}

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$inboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(z.any()).optional(),
    message: z.string().optional(),
  });

/** @internal */
export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$Outbound =
  {
    errors?: Array<any> | undefined;
    message?: string | undefined;
  };

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$outboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$Outbound,
    z.ZodTypeDef,
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status
  > = z.object({
    errors: z.array(z.any()).optional(),
    message: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$ {
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$inboundSchema` instead. */
  export const inboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$inboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$outboundSchema` instead. */
  export const outboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$outboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$Outbound` instead. */
  export type Outbound =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$Outbound;
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52StatusToJSON(
  deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status:
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status,
): string {
  return JSON.stringify(
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$outboundSchema
      .parse(deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status),
  );
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52StatusFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status' from JSON`,
  );
}

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$inboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.lazy(() =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$inboundSchema
    ).optional(),
    status: z.lazy(() =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$inboundSchema
    ).optional(),
  });

/** @internal */
export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$Outbound =
  {
    data?:
      | DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$Outbound
      | undefined;
    status?:
      | DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$Outbound
      | undefined;
  };

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$outboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$Outbound,
    z.ZodTypeDef,
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody
  > = z.object({
    data: z.lazy(() =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Data$outboundSchema
    ).optional(),
    status: z.lazy(() =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Status$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$ {
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$inboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$outboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$Outbound` instead. */
  export type Outbound =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$Outbound;
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBodyToJSON(
  deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody:
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody,
): string {
  return JSON.stringify(
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$outboundSchema
      .parse(
        deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody,
      ),
  );
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody' from JSON`,
  );
}

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$inboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())),
    Result: z.lazy(() =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$Outbound =
  {
    Headers: { [k: string]: Array<string> };
    Result:
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$Outbound;
  };

/** @internal */
export const DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$outboundSchema:
  z.ZodType<
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$Outbound,
    z.ZodTypeDef,
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: z.lazy(() =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseBody$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$ {
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$inboundSchema` instead. */
  export const inboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$inboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$outboundSchema` instead. */
  export const outboundSchema =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$outboundSchema;
  /** @deprecated use `DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$Outbound` instead. */
  export type Outbound =
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$Outbound;
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseToJSON(
  deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response:
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response,
): string {
  return JSON.stringify(
    DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$outboundSchema
      .parse(deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response),
  );
}

export function deleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52ResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteUserCustomersV1Cus17febb02B2cd4cf8B2997a447530ef52Response' from JSON`,
  );
}
