/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetClientTransactionsV1SearchRequest = {
  /**
   * Filter by transaction IDs
   */
  tokens?: string | undefined;
  /**
   * Filter by transaction states
   */
  states?: string | undefined;
  /**
   * Filter by currencies
   */
  currencies?: string | undefined;
  /**
   * Filter by instrument IDs
   */
  instrumentIds?: string | undefined;
  /**
   * Filter by subscription IDs
   */
  subscriptionIds?: string | undefined;
  /**
   * Filter by User IDs
   */
  userIds?: string | undefined;
  /**
   * Limit search results
   */
  limit?: string | undefined;
  /**
   * Paginate search results
   */
  page?: string | undefined;
  /**
   * Sort by specifies the field use to sort data e.g. `created_at`
   */
  sortBy?: string | undefined;
  /**
   * Direction specifies the data sort order either ASC or DESC
   */
  direction?: string | undefined;
};

export type GetClientTransactionsV1SearchPriceMoney = {
  amount?: string | undefined;
  currency?: string | undefined;
};

export type Transaction = {
  amount?: string | undefined;
  chargeAt?: Date | undefined;
  charged?: Date | undefined;
  createdAt?: Date | undefined;
  currency?: string | undefined;
  failures?: Array<any> | undefined;
  instrumentId?: string | undefined;
  merchantApiKey?: string | undefined;
  priceMoney?: GetClientTransactionsV1SearchPriceMoney | undefined;
  proration?: boolean | undefined;
  status?: string | undefined;
  subscription?: any | null | undefined;
  subscriptionId?: string | undefined;
  token?: string | undefined;
  tracker?: string | undefined;
  transactionType?: string | undefined;
  updatedAt?: Date | undefined;
  userId?: string | undefined;
};

export type GetClientTransactionsV1SearchData = {
  count?: number | undefined;
  direction?: string | undefined;
  sortBy?: string | undefined;
  transactions?: Array<Transaction> | undefined;
};

/**
 * 200
 */
export type GetClientTransactionsV1SearchResponseBody = {
  data?: GetClientTransactionsV1SearchData | undefined;
  status?: models.Status | undefined;
};

export type GetClientTransactionsV1SearchResponse = {
  headers: { [k: string]: Array<string> };
  result: GetClientTransactionsV1SearchResponseBody;
};

/** @internal */
export type GetClientTransactionsV1SearchRequest$Outbound = {
  tokens?: string | undefined;
  states?: string | undefined;
  currencies?: string | undefined;
  instrument_ids?: string | undefined;
  subscription_ids?: string | undefined;
  user_ids?: string | undefined;
  limit?: string | undefined;
  page?: string | undefined;
  sort_by?: string | undefined;
  direction?: string | undefined;
};

/** @internal */
export const GetClientTransactionsV1SearchRequest$outboundSchema: z.ZodType<
  GetClientTransactionsV1SearchRequest$Outbound,
  z.ZodTypeDef,
  GetClientTransactionsV1SearchRequest
> = z.object({
  tokens: z.string().optional(),
  states: z.string().optional(),
  currencies: z.string().optional(),
  instrumentIds: z.string().optional(),
  subscriptionIds: z.string().optional(),
  userIds: z.string().optional(),
  limit: z.string().optional(),
  page: z.string().optional(),
  sortBy: z.string().optional(),
  direction: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    instrumentIds: "instrument_ids",
    subscriptionIds: "subscription_ids",
    userIds: "user_ids",
    sortBy: "sort_by",
  });
});

export function getClientTransactionsV1SearchRequestToJSON(
  getClientTransactionsV1SearchRequest: GetClientTransactionsV1SearchRequest,
): string {
  return JSON.stringify(
    GetClientTransactionsV1SearchRequest$outboundSchema.parse(
      getClientTransactionsV1SearchRequest,
    ),
  );
}

/** @internal */
export const GetClientTransactionsV1SearchPriceMoney$inboundSchema: z.ZodType<
  GetClientTransactionsV1SearchPriceMoney,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.string().optional(),
  currency: z.string().optional(),
});

export function getClientTransactionsV1SearchPriceMoneyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetClientTransactionsV1SearchPriceMoney,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetClientTransactionsV1SearchPriceMoney$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetClientTransactionsV1SearchPriceMoney' from JSON`,
  );
}

/** @internal */
export const Transaction$inboundSchema: z.ZodType<
  Transaction,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.string().optional(),
  charge_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  charged: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  currency: z.string().optional(),
  failures: z.array(z.any()).optional(),
  instrument_id: z.string().optional(),
  merchant_api_key: z.string().optional(),
  price_money: z.lazy(() =>
    GetClientTransactionsV1SearchPriceMoney$inboundSchema
  ).optional(),
  proration: z.boolean().optional(),
  status: z.string().optional(),
  subscription: z.nullable(z.any()).optional(),
  subscription_id: z.string().optional(),
  token: z.string().optional(),
  tracker: z.string().optional(),
  transaction_type: z.string().optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  user_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "charge_at": "chargeAt",
    "created_at": "createdAt",
    "instrument_id": "instrumentId",
    "merchant_api_key": "merchantApiKey",
    "price_money": "priceMoney",
    "subscription_id": "subscriptionId",
    "transaction_type": "transactionType",
    "updated_at": "updatedAt",
    "user_id": "userId",
  });
});

export function transactionFromJSON(
  jsonString: string,
): SafeParseResult<Transaction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Transaction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Transaction' from JSON`,
  );
}

/** @internal */
export const GetClientTransactionsV1SearchData$inboundSchema: z.ZodType<
  GetClientTransactionsV1SearchData,
  z.ZodTypeDef,
  unknown
> = z.object({
  count: z.number().int().optional(),
  direction: z.string().optional(),
  sort_by: z.string().optional(),
  transactions: z.array(z.lazy(() => Transaction$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "sort_by": "sortBy",
  });
});

export function getClientTransactionsV1SearchDataFromJSON(
  jsonString: string,
): SafeParseResult<GetClientTransactionsV1SearchData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClientTransactionsV1SearchData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClientTransactionsV1SearchData' from JSON`,
  );
}

/** @internal */
export const GetClientTransactionsV1SearchResponseBody$inboundSchema: z.ZodType<
  GetClientTransactionsV1SearchResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => GetClientTransactionsV1SearchData$inboundSchema)
    .optional(),
  status: models.Status$inboundSchema.optional(),
});

export function getClientTransactionsV1SearchResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetClientTransactionsV1SearchResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetClientTransactionsV1SearchResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetClientTransactionsV1SearchResponseBody' from JSON`,
  );
}

/** @internal */
export const GetClientTransactionsV1SearchResponse$inboundSchema: z.ZodType<
  GetClientTransactionsV1SearchResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.lazy(() => GetClientTransactionsV1SearchResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function getClientTransactionsV1SearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetClientTransactionsV1SearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetClientTransactionsV1SearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClientTransactionsV1SearchResponse' from JSON`,
  );
}
