/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus =
  {
    errors?: Array<string> | undefined;
    message?: string | undefined;
  };

export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum =
  {
    id?: string | undefined;
    quickLinkId?: string | undefined;
    recipientViewUrl?: string | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
  };

export type Link = {
  id?: string | undefined;
  merchantId?: string | undefined;
  number?: string | undefined;
  status?: string | undefined;
  note?: string | undefined;
  metadata?:
    | Array<GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum>
    | undefined;
  payment?: Array<any> | undefined;
  recipients?: Array<any> | undefined;
  total?: number | undefined;
  currency?: string | undefined;
  workflow?: string | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient = {
  token?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  email?: string | undefined;
  phone?: string | undefined;
  apiKey?: string | undefined;
  avatar?: string | undefined;
  website?: string | undefined;
  payoutTerms?: string | undefined;
  active?: number | undefined;
  suspended?: number | undefined;
  suspendReason?: string | undefined;
  emailSettings?: any | null | undefined;
  apiSettings?: any | null | undefined;
  organization?: any | null | undefined;
  verification?: any | null | undefined;
  verified?: number | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData = {
  link?: Link | undefined;
  client?:
    | GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient
    | undefined;
};

export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus = {
  errors?: Array<any> | undefined;
  message?: string | undefined;
};

/**
 * 200
 */
export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody =
  {
    data?:
      | GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData
      | undefined;
    status?:
      | GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus
      | undefined;
  };

export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody;
  };

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$inboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(z.string()).optional(),
    message: z.string().optional(),
  });

/** @internal */
export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$Outbound =
  {
    errors?: Array<string> | undefined;
    message?: string | undefined;
  };

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$outboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$Outbound,
    z.ZodTypeDef,
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus
  > = z.object({
    errors: z.array(z.string()).optional(),
    message: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$ {
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$inboundSchema` instead. */
  export const inboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$inboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$outboundSchema` instead. */
  export const outboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$outboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$Outbound` instead. */
  export type Outbound =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$Outbound;
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatusToJSON(
  getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus:
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus,
): string {
  return JSON.stringify(
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$outboundSchema
      .parse(
        getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus,
      ),
  );
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatusFromJSON(
  jsonString: string,
): SafeParseResult<
  GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cNotFoundStatus' from JSON`,
  );
}

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$inboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    quick_link_id: z.string().optional(),
    recipient_view_url: z.string().optional(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    updated_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "quick_link_id": "quickLinkId",
      "recipient_view_url": "recipientViewUrl",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  });

/** @internal */
export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$Outbound =
  {
    id?: string | undefined;
    quick_link_id?: string | undefined;
    recipient_view_url?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
  };

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$outboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$Outbound,
    z.ZodTypeDef,
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum
  > = z.object({
    id: z.string().optional(),
    quickLinkId: z.string().optional(),
    recipientViewUrl: z.string().optional(),
    createdAt: z.date().transform(v => v.toISOString()).optional(),
    updatedAt: z.date().transform(v => v.toISOString()).optional(),
  }).transform((v) => {
    return remap$(v, {
      quickLinkId: "quick_link_id",
      recipientViewUrl: "recipient_view_url",
      createdAt: "created_at",
      updatedAt: "updated_at",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$ {
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$inboundSchema` instead. */
  export const inboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$inboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$outboundSchema` instead. */
  export const outboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$outboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$Outbound` instead. */
  export type Outbound =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$Outbound;
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatumToJSON(
  getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum:
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum,
): string {
  return JSON.stringify(
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$outboundSchema
      .parse(
        getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum,
      ),
  );
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatumFromJSON(
  jsonString: string,
): SafeParseResult<
  GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum' from JSON`,
  );
}

/** @internal */
export const Link$inboundSchema: z.ZodType<Link, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string().optional(),
    merchant_id: z.string().optional(),
    number: z.string().optional(),
    status: z.string().optional(),
    note: z.string().optional(),
    metadata: z.array(
      z.lazy(() =>
        GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$inboundSchema
      ),
    ).optional(),
    payment: z.array(z.any()).optional(),
    recipients: z.array(z.any()).optional(),
    total: z.number().int().optional(),
    currency: z.string().optional(),
    workflow: z.string().optional(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    updated_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "merchant_id": "merchantId",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  });

/** @internal */
export type Link$Outbound = {
  id?: string | undefined;
  merchant_id?: string | undefined;
  number?: string | undefined;
  status?: string | undefined;
  note?: string | undefined;
  metadata?:
    | Array<
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$Outbound
    >
    | undefined;
  payment?: Array<any> | undefined;
  recipients?: Array<any> | undefined;
  total?: number | undefined;
  currency?: string | undefined;
  workflow?: string | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
};

/** @internal */
export const Link$outboundSchema: z.ZodType<Link$Outbound, z.ZodTypeDef, Link> =
  z.object({
    id: z.string().optional(),
    merchantId: z.string().optional(),
    number: z.string().optional(),
    status: z.string().optional(),
    note: z.string().optional(),
    metadata: z.array(
      z.lazy(() =>
        GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cMetadatum$outboundSchema
      ),
    ).optional(),
    payment: z.array(z.any()).optional(),
    recipients: z.array(z.any()).optional(),
    total: z.number().int().optional(),
    currency: z.string().optional(),
    workflow: z.string().optional(),
    createdAt: z.date().transform(v => v.toISOString()).optional(),
    updatedAt: z.date().transform(v => v.toISOString()).optional(),
  }).transform((v) => {
    return remap$(v, {
      merchantId: "merchant_id",
      createdAt: "created_at",
      updatedAt: "updated_at",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Link$ {
  /** @deprecated use `Link$inboundSchema` instead. */
  export const inboundSchema = Link$inboundSchema;
  /** @deprecated use `Link$outboundSchema` instead. */
  export const outboundSchema = Link$outboundSchema;
  /** @deprecated use `Link$Outbound` instead. */
  export type Outbound = Link$Outbound;
}

export function linkToJSON(link: Link): string {
  return JSON.stringify(Link$outboundSchema.parse(link));
}

export function linkFromJSON(
  jsonString: string,
): SafeParseResult<Link, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Link$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Link' from JSON`,
  );
}

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$inboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient,
    z.ZodTypeDef,
    unknown
  > = z.object({
    token: z.string().optional(),
    name: z.string().optional(),
    description: z.string().optional(),
    email: z.string().optional(),
    phone: z.string().optional(),
    api_key: z.string().optional(),
    avatar: z.string().optional(),
    website: z.string().optional(),
    payout_terms: z.string().optional(),
    active: z.number().int().optional(),
    suspended: z.number().int().optional(),
    suspend_reason: z.string().optional(),
    email_settings: z.nullable(z.any()).optional(),
    api_settings: z.nullable(z.any()).optional(),
    organization: z.nullable(z.any()).optional(),
    verification: z.nullable(z.any()).optional(),
    verified: z.number().int().optional(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    updated_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "api_key": "apiKey",
      "payout_terms": "payoutTerms",
      "suspend_reason": "suspendReason",
      "email_settings": "emailSettings",
      "api_settings": "apiSettings",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  });

/** @internal */
export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$Outbound =
  {
    token?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    email?: string | undefined;
    phone?: string | undefined;
    api_key?: string | undefined;
    avatar?: string | undefined;
    website?: string | undefined;
    payout_terms?: string | undefined;
    active?: number | undefined;
    suspended?: number | undefined;
    suspend_reason?: string | undefined;
    email_settings?: any | null | undefined;
    api_settings?: any | null | undefined;
    organization?: any | null | undefined;
    verification?: any | null | undefined;
    verified?: number | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
  };

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$outboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$Outbound,
    z.ZodTypeDef,
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient
  > = z.object({
    token: z.string().optional(),
    name: z.string().optional(),
    description: z.string().optional(),
    email: z.string().optional(),
    phone: z.string().optional(),
    apiKey: z.string().optional(),
    avatar: z.string().optional(),
    website: z.string().optional(),
    payoutTerms: z.string().optional(),
    active: z.number().int().optional(),
    suspended: z.number().int().optional(),
    suspendReason: z.string().optional(),
    emailSettings: z.nullable(z.any()).optional(),
    apiSettings: z.nullable(z.any()).optional(),
    organization: z.nullable(z.any()).optional(),
    verification: z.nullable(z.any()).optional(),
    verified: z.number().int().optional(),
    createdAt: z.date().transform(v => v.toISOString()).optional(),
    updatedAt: z.date().transform(v => v.toISOString()).optional(),
  }).transform((v) => {
    return remap$(v, {
      apiKey: "api_key",
      payoutTerms: "payout_terms",
      suspendReason: "suspend_reason",
      emailSettings: "email_settings",
      apiSettings: "api_settings",
      createdAt: "created_at",
      updatedAt: "updated_at",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$ {
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$inboundSchema` instead. */
  export const inboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$inboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$outboundSchema` instead. */
  export const outboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$outboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$Outbound` instead. */
  export type Outbound =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$Outbound;
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClientToJSON(
  getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient:
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient,
): string {
  return JSON.stringify(
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$outboundSchema
      .parse(getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient),
  );
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClientFromJSON(
  jsonString: string,
): SafeParseResult<
  GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient' from JSON`,
  );
}

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$inboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData,
    z.ZodTypeDef,
    unknown
  > = z.object({
    link: z.lazy(() => Link$inboundSchema).optional(),
    client: z.lazy(() =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$inboundSchema
    ).optional(),
  });

/** @internal */
export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$Outbound =
  {
    link?: Link$Outbound | undefined;
    client?:
      | GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$Outbound
      | undefined;
  };

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$outboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$Outbound,
    z.ZodTypeDef,
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData
  > = z.object({
    link: z.lazy(() => Link$outboundSchema).optional(),
    client: z.lazy(() =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cClient$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$ {
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$inboundSchema` instead. */
  export const inboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$inboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$outboundSchema` instead. */
  export const outboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$outboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$Outbound` instead. */
  export type Outbound =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$Outbound;
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cDataToJSON(
  getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData:
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData,
): string {
  return JSON.stringify(
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$outboundSchema
      .parse(getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData),
  );
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData' from JSON`,
  );
}

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$inboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(z.any()).optional(),
    message: z.string().optional(),
  });

/** @internal */
export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$Outbound =
  {
    errors?: Array<any> | undefined;
    message?: string | undefined;
  };

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$outboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$Outbound,
    z.ZodTypeDef,
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus
  > = z.object({
    errors: z.array(z.any()).optional(),
    message: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$ {
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$inboundSchema` instead. */
  export const inboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$inboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$outboundSchema` instead. */
  export const outboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$outboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$Outbound` instead. */
  export type Outbound =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$Outbound;
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatusToJSON(
  getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus:
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus,
): string {
  return JSON.stringify(
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$outboundSchema
      .parse(getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus),
  );
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatusFromJSON(
  jsonString: string,
): SafeParseResult<
  GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus' from JSON`,
  );
}

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$inboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.lazy(() =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$inboundSchema
    ).optional(),
    status: z.lazy(() =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$inboundSchema
    ).optional(),
  });

/** @internal */
export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$Outbound =
  {
    data?:
      | GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$Outbound
      | undefined;
    status?:
      | GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$Outbound
      | undefined;
  };

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$outboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$Outbound,
    z.ZodTypeDef,
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody
  > = z.object({
    data: z.lazy(() =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cData$outboundSchema
    ).optional(),
    status: z.lazy(() =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cStatus$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$ {
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$inboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$outboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$Outbound` instead. */
  export type Outbound =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$Outbound;
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBodyToJSON(
  getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody:
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody,
): string {
  return JSON.stringify(
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$outboundSchema
      .parse(
        getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody,
      ),
  );
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody' from JSON`,
  );
}

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$inboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())),
    Result: z.lazy(() =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$Outbound =
  {
    Headers: { [k: string]: Array<string> };
    Result:
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$Outbound;
  };

/** @internal */
export const GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$outboundSchema:
  z.ZodType<
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$Outbound,
    z.ZodTypeDef,
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: z.lazy(() =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseBody$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$ {
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$inboundSchema` instead. */
  export const inboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$inboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$outboundSchema` instead. */
  export const outboundSchema =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$outboundSchema;
  /** @deprecated use `GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$Outbound` instead. */
  export type Outbound =
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$Outbound;
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseToJSON(
  getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse:
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse,
): string {
  return JSON.stringify(
    GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$outboundSchema
      .parse(
        getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse,
      ),
  );
}

export function getInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetInvoiceQuickLinksV1Link297bfa4bF61c4c7280a4368d731e890cResponse' from JSON`,
  );
}
