/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetReporterApiV1PaymentsRequest = {
  /**
   * Limit search results to a value
   */
  limit?: number | undefined;
  /**
   * Paginate search results
   */
  page?: number | undefined;
  /**
   * Sort by specifies the field use to sort data e.g. `created_at`
   */
  sortBy?: string | undefined;
  /**
   * Direction specifies the data sort order either ASC or DESC
   */
  direction?: string | undefined;
};

export type Client = {
  apiKey?: string | undefined;
};

export type GetReporterApiV1PaymentsCreatedAt = {
  seconds?: number | undefined;
};

export type GetReporterApiV1PaymentsCustomer = {
  token?: string | undefined;
};

export type GetReporterApiV1PaymentsList = {
  client?: Client | undefined;
  createdAt?: GetReporterApiV1PaymentsCreatedAt | undefined;
  currency?: string | undefined;
  customer?: GetReporterApiV1PaymentsCustomer | undefined;
  displayAmount?: string | undefined;
  environment?: string | undefined;
  intent?: string | undefined;
  mode?: string | undefined;
  state?: string | undefined;
  token?: string | undefined;
};

export type Meta = {
  direction?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  page?: number | undefined;
  sortBy?: string | undefined;
};

export type GetReporterApiV1PaymentsData = {
  count?: number | undefined;
  list?: Array<GetReporterApiV1PaymentsList> | undefined;
  meta?: Meta | undefined;
};

/**
 * 200
 */
export type GetReporterApiV1PaymentsResponseBody = {
  data?: GetReporterApiV1PaymentsData | undefined;
  ok?: boolean | undefined;
  status?: models.Status | undefined;
};

export type GetReporterApiV1PaymentsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetReporterApiV1PaymentsResponseBody;
};

/** @internal */
export type GetReporterApiV1PaymentsRequest$Outbound = {
  limit?: number | undefined;
  page?: number | undefined;
  sort_by?: string | undefined;
  direction?: string | undefined;
};

/** @internal */
export const GetReporterApiV1PaymentsRequest$outboundSchema: z.ZodType<
  GetReporterApiV1PaymentsRequest$Outbound,
  z.ZodTypeDef,
  GetReporterApiV1PaymentsRequest
> = z.object({
  limit: z.number().int().optional(),
  page: z.number().int().optional(),
  sortBy: z.string().optional(),
  direction: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    sortBy: "sort_by",
  });
});

export function getReporterApiV1PaymentsRequestToJSON(
  getReporterApiV1PaymentsRequest: GetReporterApiV1PaymentsRequest,
): string {
  return JSON.stringify(
    GetReporterApiV1PaymentsRequest$outboundSchema.parse(
      getReporterApiV1PaymentsRequest,
    ),
  );
}

/** @internal */
export const Client$inboundSchema: z.ZodType<Client, z.ZodTypeDef, unknown> = z
  .object({
    api_key: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "api_key": "apiKey",
    });
  });

export function clientFromJSON(
  jsonString: string,
): SafeParseResult<Client, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Client$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Client' from JSON`,
  );
}

/** @internal */
export const GetReporterApiV1PaymentsCreatedAt$inboundSchema: z.ZodType<
  GetReporterApiV1PaymentsCreatedAt,
  z.ZodTypeDef,
  unknown
> = z.object({
  seconds: z.number().int().optional(),
});

export function getReporterApiV1PaymentsCreatedAtFromJSON(
  jsonString: string,
): SafeParseResult<GetReporterApiV1PaymentsCreatedAt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetReporterApiV1PaymentsCreatedAt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetReporterApiV1PaymentsCreatedAt' from JSON`,
  );
}

/** @internal */
export const GetReporterApiV1PaymentsCustomer$inboundSchema: z.ZodType<
  GetReporterApiV1PaymentsCustomer,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: z.string().optional(),
});

export function getReporterApiV1PaymentsCustomerFromJSON(
  jsonString: string,
): SafeParseResult<GetReporterApiV1PaymentsCustomer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetReporterApiV1PaymentsCustomer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetReporterApiV1PaymentsCustomer' from JSON`,
  );
}

/** @internal */
export const GetReporterApiV1PaymentsList$inboundSchema: z.ZodType<
  GetReporterApiV1PaymentsList,
  z.ZodTypeDef,
  unknown
> = z.object({
  client: z.lazy(() => Client$inboundSchema).optional(),
  created_at: z.lazy(() => GetReporterApiV1PaymentsCreatedAt$inboundSchema)
    .optional(),
  currency: z.string().optional(),
  customer: z.lazy(() => GetReporterApiV1PaymentsCustomer$inboundSchema)
    .optional(),
  display_amount: z.string().optional(),
  environment: z.string().optional(),
  intent: z.string().optional(),
  mode: z.string().optional(),
  state: z.string().optional(),
  token: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "display_amount": "displayAmount",
  });
});

export function getReporterApiV1PaymentsListFromJSON(
  jsonString: string,
): SafeParseResult<GetReporterApiV1PaymentsList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetReporterApiV1PaymentsList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetReporterApiV1PaymentsList' from JSON`,
  );
}

/** @internal */
export const Meta$inboundSchema: z.ZodType<Meta, z.ZodTypeDef, unknown> = z
  .object({
    direction: z.string().optional(),
    limit: z.number().int().optional(),
    offset: z.number().int().optional(),
    page: z.number().int().optional(),
    sort_by: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "sort_by": "sortBy",
    });
  });

export function metaFromJSON(
  jsonString: string,
): SafeParseResult<Meta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Meta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Meta' from JSON`,
  );
}

/** @internal */
export const GetReporterApiV1PaymentsData$inboundSchema: z.ZodType<
  GetReporterApiV1PaymentsData,
  z.ZodTypeDef,
  unknown
> = z.object({
  count: z.number().int().optional(),
  list: z.array(z.lazy(() => GetReporterApiV1PaymentsList$inboundSchema))
    .optional(),
  meta: z.lazy(() => Meta$inboundSchema).optional(),
});

export function getReporterApiV1PaymentsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetReporterApiV1PaymentsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetReporterApiV1PaymentsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetReporterApiV1PaymentsData' from JSON`,
  );
}

/** @internal */
export const GetReporterApiV1PaymentsResponseBody$inboundSchema: z.ZodType<
  GetReporterApiV1PaymentsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => GetReporterApiV1PaymentsData$inboundSchema).optional(),
  ok: z.boolean().optional(),
  status: models.Status$inboundSchema.optional(),
});

export function getReporterApiV1PaymentsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetReporterApiV1PaymentsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetReporterApiV1PaymentsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetReporterApiV1PaymentsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetReporterApiV1PaymentsResponse$inboundSchema: z.ZodType<
  GetReporterApiV1PaymentsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.lazy(() => GetReporterApiV1PaymentsResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function getReporterApiV1PaymentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetReporterApiV1PaymentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetReporterApiV1PaymentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetReporterApiV1PaymentsResponse' from JSON`,
  );
}
