/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetUserCustomersV1Request = {
  limit?: number | undefined;
  page?: number | undefined;
};

export type GetUserCustomersV1CreatedAt = {
  seconds?: number | undefined;
};

export type GetUserCustomersV1UpdatedAt = {
  seconds?: number | undefined;
};

export type GetUserCustomersV1Customer = {
  country?: string | undefined;
  createdAt?: GetUserCustomersV1CreatedAt | undefined;
  email?: string | undefined;
  firstName?: string | undefined;
  isDeleted?: boolean | undefined;
  isGuest?: boolean | undefined;
  lastName?: string | undefined;
  merchantApiKey?: string | undefined;
  phoneNumber?: string | undefined;
  token?: string | undefined;
  updatedAt?: GetUserCustomersV1UpdatedAt | undefined;
};

export type GetUserCustomersV1Data = {
  count?: number | undefined;
  customers?: Array<GetUserCustomersV1Customer> | undefined;
};

/**
 * 200
 */
export type GetUserCustomersV1ResponseBody = {
  data?: GetUserCustomersV1Data | undefined;
  status?: models.Status | undefined;
};

export type GetUserCustomersV1Response = {
  headers: { [k: string]: Array<string> };
  result: GetUserCustomersV1ResponseBody;
};

/** @internal */
export type GetUserCustomersV1Request$Outbound = {
  limit?: number | undefined;
  page?: number | undefined;
};

/** @internal */
export const GetUserCustomersV1Request$outboundSchema: z.ZodType<
  GetUserCustomersV1Request$Outbound,
  z.ZodTypeDef,
  GetUserCustomersV1Request
> = z.object({
  limit: z.number().int().optional(),
  page: z.number().int().optional(),
});

export function getUserCustomersV1RequestToJSON(
  getUserCustomersV1Request: GetUserCustomersV1Request,
): string {
  return JSON.stringify(
    GetUserCustomersV1Request$outboundSchema.parse(getUserCustomersV1Request),
  );
}

/** @internal */
export const GetUserCustomersV1CreatedAt$inboundSchema: z.ZodType<
  GetUserCustomersV1CreatedAt,
  z.ZodTypeDef,
  unknown
> = z.object({
  seconds: z.number().int().optional(),
});

export function getUserCustomersV1CreatedAtFromJSON(
  jsonString: string,
): SafeParseResult<GetUserCustomersV1CreatedAt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserCustomersV1CreatedAt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserCustomersV1CreatedAt' from JSON`,
  );
}

/** @internal */
export const GetUserCustomersV1UpdatedAt$inboundSchema: z.ZodType<
  GetUserCustomersV1UpdatedAt,
  z.ZodTypeDef,
  unknown
> = z.object({
  seconds: z.number().int().optional(),
});

export function getUserCustomersV1UpdatedAtFromJSON(
  jsonString: string,
): SafeParseResult<GetUserCustomersV1UpdatedAt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserCustomersV1UpdatedAt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserCustomersV1UpdatedAt' from JSON`,
  );
}

/** @internal */
export const GetUserCustomersV1Customer$inboundSchema: z.ZodType<
  GetUserCustomersV1Customer,
  z.ZodTypeDef,
  unknown
> = z.object({
  country: z.string().optional(),
  created_at: z.lazy(() => GetUserCustomersV1CreatedAt$inboundSchema)
    .optional(),
  email: z.string().optional(),
  first_name: z.string().optional(),
  is_deleted: z.boolean().optional(),
  is_guest: z.boolean().optional(),
  last_name: z.string().optional(),
  merchant_api_key: z.string().optional(),
  phone_number: z.string().optional(),
  token: z.string().optional(),
  updated_at: z.lazy(() => GetUserCustomersV1UpdatedAt$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "first_name": "firstName",
    "is_deleted": "isDeleted",
    "is_guest": "isGuest",
    "last_name": "lastName",
    "merchant_api_key": "merchantApiKey",
    "phone_number": "phoneNumber",
    "updated_at": "updatedAt",
  });
});

export function getUserCustomersV1CustomerFromJSON(
  jsonString: string,
): SafeParseResult<GetUserCustomersV1Customer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserCustomersV1Customer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserCustomersV1Customer' from JSON`,
  );
}

/** @internal */
export const GetUserCustomersV1Data$inboundSchema: z.ZodType<
  GetUserCustomersV1Data,
  z.ZodTypeDef,
  unknown
> = z.object({
  count: z.number().int().optional(),
  customers: z.array(z.lazy(() => GetUserCustomersV1Customer$inboundSchema))
    .optional(),
});

export function getUserCustomersV1DataFromJSON(
  jsonString: string,
): SafeParseResult<GetUserCustomersV1Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserCustomersV1Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserCustomersV1Data' from JSON`,
  );
}

/** @internal */
export const GetUserCustomersV1ResponseBody$inboundSchema: z.ZodType<
  GetUserCustomersV1ResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => GetUserCustomersV1Data$inboundSchema).optional(),
  status: models.Status$inboundSchema.optional(),
});

export function getUserCustomersV1ResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetUserCustomersV1ResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserCustomersV1ResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserCustomersV1ResponseBody' from JSON`,
  );
}

/** @internal */
export const GetUserCustomersV1Response$inboundSchema: z.ZodType<
  GetUserCustomersV1Response,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.lazy(() => GetUserCustomersV1ResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function getUserCustomersV1ResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUserCustomersV1Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserCustomersV1Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserCustomersV1Response' from JSON`,
  );
}
