/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus =
  {
    errors?: Array<string> | undefined;
    message?: string | undefined;
  };

export type PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction =
  {
    token?: string | undefined;
    chargeAt?: Date | undefined;
    status?: string | undefined;
    amount?: string | undefined;
    currency?: string | undefined;
    instrumentId?: string | undefined;
    subscriptionId?: string | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    failures?: Array<any> | undefined;
    subscription?: any | null | undefined;
    merchantApiKey?: string | undefined;
    userId?: string | undefined;
    transactionType?: string | undefined;
    proration?: boolean | undefined;
    tracker?: string | undefined;
  };

export type PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData =
  {
    transaction?:
      | PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction
      | undefined;
  };

/**
 * 200
 */
export type PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody =
  {
    data?:
      | PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData
      | undefined;
  };

export type PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody;
  };

/** @internal */
export const PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$inboundSchema:
  z.ZodType<
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(z.string()).optional(),
    message: z.string().optional(),
  });

/** @internal */
export type PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$Outbound =
  {
    errors?: Array<string> | undefined;
    message?: string | undefined;
  };

/** @internal */
export const PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$outboundSchema:
  z.ZodType<
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$Outbound,
    z.ZodTypeDef,
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus
  > = z.object({
    errors: z.array(z.string()).optional(),
    message: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$ {
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$inboundSchema` instead. */
  export const inboundSchema =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$inboundSchema;
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$outboundSchema` instead. */
  export const outboundSchema =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$outboundSchema;
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$Outbound` instead. */
  export type Outbound =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$Outbound;
}

export function postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatusToJSON(
  postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus:
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus,
): string {
  return JSON.stringify(
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$outboundSchema
      .parse(
        postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus,
      ),
  );
}

export function postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatusFromJSON(
  jsonString: string,
): SafeParseResult<
  PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundStatus' from JSON`,
  );
}

/** @internal */
export const PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$inboundSchema:
  z.ZodType<
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction,
    z.ZodTypeDef,
    unknown
  > = z.object({
    token: z.string().optional(),
    charge_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    status: z.string().optional(),
    amount: z.string().optional(),
    currency: z.string().optional(),
    instrument_id: z.string().optional(),
    subscription_id: z.string().optional(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    updated_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    failures: z.array(z.any()).optional(),
    subscription: z.nullable(z.any()).optional(),
    merchant_api_key: z.string().optional(),
    user_id: z.string().optional(),
    transaction_type: z.string().optional(),
    proration: z.boolean().optional(),
    tracker: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "charge_at": "chargeAt",
      "instrument_id": "instrumentId",
      "subscription_id": "subscriptionId",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "merchant_api_key": "merchantApiKey",
      "user_id": "userId",
      "transaction_type": "transactionType",
    });
  });

/** @internal */
export type PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$Outbound =
  {
    token?: string | undefined;
    charge_at?: string | undefined;
    status?: string | undefined;
    amount?: string | undefined;
    currency?: string | undefined;
    instrument_id?: string | undefined;
    subscription_id?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    failures?: Array<any> | undefined;
    subscription?: any | null | undefined;
    merchant_api_key?: string | undefined;
    user_id?: string | undefined;
    transaction_type?: string | undefined;
    proration?: boolean | undefined;
    tracker?: string | undefined;
  };

/** @internal */
export const PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$outboundSchema:
  z.ZodType<
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$Outbound,
    z.ZodTypeDef,
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction
  > = z.object({
    token: z.string().optional(),
    chargeAt: z.date().transform(v => v.toISOString()).optional(),
    status: z.string().optional(),
    amount: z.string().optional(),
    currency: z.string().optional(),
    instrumentId: z.string().optional(),
    subscriptionId: z.string().optional(),
    createdAt: z.date().transform(v => v.toISOString()).optional(),
    updatedAt: z.date().transform(v => v.toISOString()).optional(),
    failures: z.array(z.any()).optional(),
    subscription: z.nullable(z.any()).optional(),
    merchantApiKey: z.string().optional(),
    userId: z.string().optional(),
    transactionType: z.string().optional(),
    proration: z.boolean().optional(),
    tracker: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      chargeAt: "charge_at",
      instrumentId: "instrument_id",
      subscriptionId: "subscription_id",
      createdAt: "created_at",
      updatedAt: "updated_at",
      merchantApiKey: "merchant_api_key",
      userId: "user_id",
      transactionType: "transaction_type",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$ {
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$inboundSchema` instead. */
  export const inboundSchema =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$inboundSchema;
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$outboundSchema` instead. */
  export const outboundSchema =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$outboundSchema;
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$Outbound` instead. */
  export type Outbound =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$Outbound;
}

export function postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransactionToJSON(
  postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction:
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction,
): string {
  return JSON.stringify(
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$outboundSchema
      .parse(
        postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction,
      ),
  );
}

export function postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransactionFromJSON(
  jsonString: string,
): SafeParseResult<
  PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction' from JSON`,
  );
}

/** @internal */
export const PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$inboundSchema:
  z.ZodType<
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData,
    z.ZodTypeDef,
    unknown
  > = z.object({
    transaction: z.lazy(() =>
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$inboundSchema
    ).optional(),
  });

/** @internal */
export type PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$Outbound =
  {
    transaction?:
      | PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$Outbound
      | undefined;
  };

/** @internal */
export const PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$outboundSchema:
  z.ZodType<
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$Outbound,
    z.ZodTypeDef,
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData
  > = z.object({
    transaction: z.lazy(() =>
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundTransaction$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$ {
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$inboundSchema` instead. */
  export const inboundSchema =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$inboundSchema;
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$outboundSchema` instead. */
  export const outboundSchema =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$outboundSchema;
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$Outbound` instead. */
  export type Outbound =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$Outbound;
}

export function postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundDataToJSON(
  postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData:
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData,
): string {
  return JSON.stringify(
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$outboundSchema
      .parse(
        postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData,
      ),
  );
}

export function postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundDataFromJSON(
  jsonString: string,
): SafeParseResult<
  PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData' from JSON`,
  );
}

/** @internal */
export const PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$inboundSchema:
  z.ZodType<
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.lazy(() =>
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$inboundSchema
    ).optional(),
  });

/** @internal */
export type PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$Outbound =
  {
    data?:
      | PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$Outbound
      | undefined;
  };

/** @internal */
export const PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$outboundSchema:
  z.ZodType<
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$Outbound,
    z.ZodTypeDef,
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody
  > = z.object({
    data: z.lazy(() =>
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundData$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$ {
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$inboundSchema;
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$outboundSchema;
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$Outbound` instead. */
  export type Outbound =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$Outbound;
}

export function postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBodyToJSON(
  postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody:
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody,
): string {
  return JSON.stringify(
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$outboundSchema
      .parse(
        postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody,
      ),
  );
}

export function postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody' from JSON`,
  );
}

/** @internal */
export const PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$inboundSchema:
  z.ZodType<
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())),
    Result: z.lazy(() =>
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$Outbound =
  {
    Headers: { [k: string]: Array<string> };
    Result:
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$Outbound;
  };

/** @internal */
export const PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$outboundSchema:
  z.ZodType<
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$Outbound,
    z.ZodTypeDef,
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: z.lazy(() =>
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseBody$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$ {
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$inboundSchema` instead. */
  export const inboundSchema =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$inboundSchema;
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$outboundSchema` instead. */
  export const outboundSchema =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$outboundSchema;
  /** @deprecated use `PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$Outbound` instead. */
  export type Outbound =
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$Outbound;
}

export function postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseToJSON(
  postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse:
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse,
): string {
  return JSON.stringify(
    PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$outboundSchema
      .parse(
        postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse,
      ),
  );
}

export function postClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostClientTransactionsV1Txn17553398B91d41e9Ae47165e194d06a1RefundResponse' from JSON`,
  );
}
