/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request =
  {};

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE =
  {
    kind?: string | undefined;
    requestId?: string | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions =
  {
    cybersource?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE
      | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount =
  {
    currency?: string | undefined;
    amount?: number | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount =
  {
    currency?: string | undefined;
    amount?: number | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate =
  {
    baseCurrency?: string | undefined;
    quoteCurrency?: string | undefined;
    rate?: number | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals =
  {
    quoteAmount?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount
      | undefined;
    baseAmount?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount
      | undefined;
    conversionRate?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate
      | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker = {
  token?: string | undefined;
  client?: string | undefined;
  environment?: string | undefined;
  state?: string | undefined;
  intent?: string | undefined;
  mode?: string | undefined;
  nextActions?:
    | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions
    | undefined;
  purchaseTotals?:
    | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals
    | undefined;
};

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod =
  {
    token?: string | undefined;
    expirationMonth?: string | undefined;
    expirationYear?: string | undefined;
    cardTypeCode?: string | undefined;
    cardType?: string | undefined;
    binNumber?: string | undefined;
    lastFour?: string | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action = {
  token?: string | undefined;
  paymentMethod?:
    | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod
    | undefined;
};

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data = {
  tracker?:
    | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker
    | undefined;
  action?:
    | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action
    | undefined;
};

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status = {
  errors?: Array<any> | undefined;
  message?: string | undefined;
};

/**
 * 200
 */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody =
  {
    data?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data
      | undefined;
    status?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status
      | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response = {
  headers: { [k: string]: Array<string> };
  result: PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody;
};

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$Outbound =
  {};

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7RequestToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$outboundSchema
      .parse(postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7RequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Request' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE,
    z.ZodTypeDef,
    unknown
  > = z.object({
    kind: z.string().optional(),
    request_id: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$Outbound =
  {
    kind?: string | undefined;
    request_id?: string | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE
  > = z.object({
    kind: z.string().optional(),
    requestId: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      requestId: "request_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCEToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCEFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions,
    z.ZodTypeDef,
    unknown
  > = z.object({
    CYBERSOURCE: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$inboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "CYBERSOURCE": "cybersource",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$Outbound =
  {
    CYBERSOURCE?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions
  > = z.object({
    cybersource: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7CYBERSOURCE$outboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      cybersource: "CYBERSOURCE",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActionsToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActionsFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount,
    z.ZodTypeDef,
    unknown
  > = z.object({
    currency: z.string().optional(),
    amount: z.number().int().optional(),
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$Outbound =
  {
    currency?: string | undefined;
    amount?: number | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount
  > = z.object({
    currency: z.string().optional(),
    amount: z.number().int().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmountToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmountFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount,
    z.ZodTypeDef,
    unknown
  > = z.object({
    currency: z.string().optional(),
    amount: z.number().int().optional(),
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$Outbound =
  {
    currency?: string | undefined;
    amount?: number | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount
  > = z.object({
    currency: z.string().optional(),
    amount: z.number().int().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmountToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmountFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate,
    z.ZodTypeDef,
    unknown
  > = z.object({
    base_currency: z.string().optional(),
    quote_currency: z.string().optional(),
    rate: z.number().int().optional(),
  }).transform((v) => {
    return remap$(v, {
      "base_currency": "baseCurrency",
      "quote_currency": "quoteCurrency",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$Outbound =
  {
    base_currency?: string | undefined;
    quote_currency?: string | undefined;
    rate?: number | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate
  > = z.object({
    baseCurrency: z.string().optional(),
    quoteCurrency: z.string().optional(),
    rate: z.number().int().optional(),
  }).transform((v) => {
    return remap$(v, {
      baseCurrency: "base_currency",
      quoteCurrency: "quote_currency",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRateToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRateFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals,
    z.ZodTypeDef,
    unknown
  > = z.object({
    quote_amount: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$inboundSchema
    ).optional(),
    base_amount: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$inboundSchema
    ).optional(),
    conversion_rate: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$inboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "quote_amount": "quoteAmount",
      "base_amount": "baseAmount",
      "conversion_rate": "conversionRate",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$Outbound =
  {
    quote_amount?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$Outbound
      | undefined;
    base_amount?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$Outbound
      | undefined;
    conversion_rate?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals
  > = z.object({
    quoteAmount: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7QuoteAmount$outboundSchema
    ).optional(),
    baseAmount: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7BaseAmount$outboundSchema
    ).optional(),
    conversionRate: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ConversionRate$outboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      quoteAmount: "quote_amount",
      baseAmount: "base_amount",
      conversionRate: "conversion_rate",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotalsToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotalsFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker,
    z.ZodTypeDef,
    unknown
  > = z.object({
    token: z.string().optional(),
    client: z.string().optional(),
    environment: z.string().optional(),
    state: z.string().optional(),
    intent: z.string().optional(),
    mode: z.string().optional(),
    next_actions: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$inboundSchema
    ).optional(),
    purchase_totals: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$inboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "next_actions": "nextActions",
      "purchase_totals": "purchaseTotals",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$Outbound =
  {
    token?: string | undefined;
    client?: string | undefined;
    environment?: string | undefined;
    state?: string | undefined;
    intent?: string | undefined;
    mode?: string | undefined;
    next_actions?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$Outbound
      | undefined;
    purchase_totals?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker
  > = z.object({
    token: z.string().optional(),
    client: z.string().optional(),
    environment: z.string().optional(),
    state: z.string().optional(),
    intent: z.string().optional(),
    mode: z.string().optional(),
    nextActions: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7NextActions$outboundSchema
    ).optional(),
    purchaseTotals: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PurchaseTotals$outboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      nextActions: "next_actions",
      purchaseTotals: "purchase_totals",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7TrackerToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$outboundSchema
      .parse(postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7TrackerFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod,
    z.ZodTypeDef,
    unknown
  > = z.object({
    token: z.string().optional(),
    expiration_month: z.string().optional(),
    expiration_year: z.string().optional(),
    card_type_code: z.string().optional(),
    card_type: z.string().optional(),
    bin_number: z.string().optional(),
    last_four: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "expiration_month": "expirationMonth",
      "expiration_year": "expirationYear",
      "card_type_code": "cardTypeCode",
      "card_type": "cardType",
      "bin_number": "binNumber",
      "last_four": "lastFour",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$Outbound =
  {
    token?: string | undefined;
    expiration_month?: string | undefined;
    expiration_year?: string | undefined;
    card_type_code?: string | undefined;
    card_type?: string | undefined;
    bin_number?: string | undefined;
    last_four?: string | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod
  > = z.object({
    token: z.string().optional(),
    expirationMonth: z.string().optional(),
    expirationYear: z.string().optional(),
    cardTypeCode: z.string().optional(),
    cardType: z.string().optional(),
    binNumber: z.string().optional(),
    lastFour: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      expirationMonth: "expiration_month",
      expirationYear: "expiration_year",
      cardTypeCode: "card_type_code",
      cardType: "card_type",
      binNumber: "bin_number",
      lastFour: "last_four",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethodToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethodFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action,
    z.ZodTypeDef,
    unknown
  > = z.object({
    token: z.string().optional(),
    payment_method: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$inboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "payment_method": "paymentMethod",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$Outbound =
  {
    token?: string | undefined;
    payment_method?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action
  > = z.object({
    token: z.string().optional(),
    paymentMethod: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7PaymentMethod$outboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      paymentMethod: "payment_method",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ActionToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$outboundSchema
      .parse(postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ActionFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data,
    z.ZodTypeDef,
    unknown
  > = z.object({
    tracker: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$inboundSchema
    ).optional(),
    action: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$inboundSchema
    ).optional(),
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$Outbound =
  {
    tracker?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$Outbound
      | undefined;
    action?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data
  > = z.object({
    tracker: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Tracker$outboundSchema
    ).optional(),
    action: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Action$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7DataToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$outboundSchema
      .parse(postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7DataFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(z.any()).optional(),
    message: z.string().optional(),
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$Outbound =
  {
    errors?: Array<any> | undefined;
    message?: string | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status
  > = z.object({
    errors: z.array(z.any()).optional(),
    message: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7StatusToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$outboundSchema
      .parse(postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7StatusFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$inboundSchema
    ).optional(),
    status: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$inboundSchema
    ).optional(),
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$Outbound =
  {
    data?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$Outbound
      | undefined;
    status?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody
  > = z.object({
    data: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Data$outboundSchema
    ).optional(),
    status: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Status$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBodyToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())),
    Result: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$Outbound =
  {
    Headers: { [k: string]: Array<string> };
    Result:
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$Outbound;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseBody$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$outboundSchema
      .parse(postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7ResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7Response' from JSON`,
  );
}
