/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest =
  {
    kind?: string | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus =
  {
    errors?: Array<string> | undefined;
    message?: string | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE =
  {
    kind?: string | undefined;
    requestId?: string | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions =
  {
    cybersource?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE
      | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount =
  {
    currency?: string | undefined;
    amount?: number | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount =
  {
    currency?: string | undefined;
    amount?: number | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate =
  {
    baseCurrency?: string | undefined;
    quoteCurrency?: string | undefined;
    rate?: number | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals =
  {
    quoteAmount?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount
      | undefined;
    baseAmount?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount
      | undefined;
    conversionRate?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate
      | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker =
  {
    token?: string | undefined;
    client?: string | undefined;
    environment?: string | undefined;
    state?: string | undefined;
    intent?: string | undefined;
    mode?: string | undefined;
    nextActions?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions
      | undefined;
    purchaseTotals?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals
      | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction =
  {};

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData = {
  tracker?:
    | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker
    | undefined;
  action?:
    | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction
    | undefined;
};

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus =
  {
    errors?: Array<any> | undefined;
    message?: string | undefined;
  };

/**
 * 200 - Capture
 */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody =
  {
    data?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData
      | undefined;
    status?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus
      | undefined;
  };

export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    kind: z.string().optional(),
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$Outbound =
  {
    kind?: string | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest
  > = z.object({
    kind: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequestToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidRequest' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(z.string()).optional(),
    message: z.string().optional(),
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$Outbound =
  {
    errors?: Array<string> | undefined;
    message?: string | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus
  > = z.object({
    errors: z.array(z.string()).optional(),
    message: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatusToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatusFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBadRequestStatus' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE,
    z.ZodTypeDef,
    unknown
  > = z.object({
    kind: z.string().optional(),
    request_id: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$Outbound =
  {
    kind?: string | undefined;
    request_id?: string | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE
  > = z.object({
    kind: z.string().optional(),
    requestId: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      requestId: "request_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCEToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCEFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions,
    z.ZodTypeDef,
    unknown
  > = z.object({
    CYBERSOURCE: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$inboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "CYBERSOURCE": "cybersource",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$Outbound =
  {
    CYBERSOURCE?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions
  > = z.object({
    cybersource: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidCYBERSOURCE$outboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      cybersource: "CYBERSOURCE",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActionsToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActionsFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount,
    z.ZodTypeDef,
    unknown
  > = z.object({
    currency: z.string().optional(),
    amount: z.number().int().optional(),
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$Outbound =
  {
    currency?: string | undefined;
    amount?: number | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount
  > = z.object({
    currency: z.string().optional(),
    amount: z.number().int().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmountToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmountFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount,
    z.ZodTypeDef,
    unknown
  > = z.object({
    currency: z.string().optional(),
    amount: z.number().int().optional(),
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$Outbound =
  {
    currency?: string | undefined;
    amount?: number | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount
  > = z.object({
    currency: z.string().optional(),
    amount: z.number().int().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmountToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmountFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate,
    z.ZodTypeDef,
    unknown
  > = z.object({
    base_currency: z.string().optional(),
    quote_currency: z.string().optional(),
    rate: z.number().int().optional(),
  }).transform((v) => {
    return remap$(v, {
      "base_currency": "baseCurrency",
      "quote_currency": "quoteCurrency",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$Outbound =
  {
    base_currency?: string | undefined;
    quote_currency?: string | undefined;
    rate?: number | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate
  > = z.object({
    baseCurrency: z.string().optional(),
    quoteCurrency: z.string().optional(),
    rate: z.number().int().optional(),
  }).transform((v) => {
    return remap$(v, {
      baseCurrency: "base_currency",
      quoteCurrency: "quote_currency",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRateToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRateFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals,
    z.ZodTypeDef,
    unknown
  > = z.object({
    quote_amount: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$inboundSchema
    ).optional(),
    base_amount: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$inboundSchema
    ).optional(),
    conversion_rate: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$inboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "quote_amount": "quoteAmount",
      "base_amount": "baseAmount",
      "conversion_rate": "conversionRate",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$Outbound =
  {
    quote_amount?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$Outbound
      | undefined;
    base_amount?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$Outbound
      | undefined;
    conversion_rate?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals
  > = z.object({
    quoteAmount: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidQuoteAmount$outboundSchema
    ).optional(),
    baseAmount: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidBaseAmount$outboundSchema
    ).optional(),
    conversionRate: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidConversionRate$outboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      quoteAmount: "quote_amount",
      baseAmount: "base_amount",
      conversionRate: "conversion_rate",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotalsToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotalsFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker,
    z.ZodTypeDef,
    unknown
  > = z.object({
    token: z.string().optional(),
    client: z.string().optional(),
    environment: z.string().optional(),
    state: z.string().optional(),
    intent: z.string().optional(),
    mode: z.string().optional(),
    next_actions: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$inboundSchema
    ).optional(),
    purchase_totals: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$inboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "next_actions": "nextActions",
      "purchase_totals": "purchaseTotals",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$Outbound =
  {
    token?: string | undefined;
    client?: string | undefined;
    environment?: string | undefined;
    state?: string | undefined;
    intent?: string | undefined;
    mode?: string | undefined;
    next_actions?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$Outbound
      | undefined;
    purchase_totals?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker
  > = z.object({
    token: z.string().optional(),
    client: z.string().optional(),
    environment: z.string().optional(),
    state: z.string().optional(),
    intent: z.string().optional(),
    mode: z.string().optional(),
    nextActions: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidNextActions$outboundSchema
    ).optional(),
    purchaseTotals: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidPurchaseTotals$outboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      nextActions: "next_actions",
      purchaseTotals: "purchase_totals",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTrackerToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTrackerFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$Outbound =
  {};

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidActionToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidActionFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData,
    z.ZodTypeDef,
    unknown
  > = z.object({
    tracker: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$inboundSchema
    ).optional(),
    action: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$inboundSchema
    ).optional(),
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$Outbound =
  {
    tracker?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$Outbound
      | undefined;
    action?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData
  > = z.object({
    tracker: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidTracker$outboundSchema
    ).optional(),
    action: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidAction$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidDataToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$outboundSchema
      .parse(postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidDataFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(z.any()).optional(),
    message: z.string().optional(),
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$Outbound =
  {
    errors?: Array<any> | undefined;
    message?: string | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus
  > = z.object({
    errors: z.array(z.any()).optional(),
    message: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatusToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatusFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$inboundSchema
    ).optional(),
    status: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$inboundSchema
    ).optional(),
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$Outbound =
  {
    data?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$Outbound
      | undefined;
    status?:
      | PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$Outbound
      | undefined;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody
  > = z.object({
    data: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidData$outboundSchema
    ).optional(),
    status: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidStatus$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBodyToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody' from JSON`,
  );
}

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$inboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())),
    Result: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$Outbound =
  {
    Headers: { [k: string]: Array<string> };
    Result:
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$Outbound;
  };

/** @internal */
export const PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$outboundSchema:
  z.ZodType<
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$Outbound,
    z.ZodTypeDef,
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: z.lazy(() =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseBody$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$ {
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$inboundSchema` instead. */
  export const inboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$inboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$outboundSchema` instead. */
  export const outboundSchema =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$outboundSchema;
  /** @deprecated use `PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$Outbound` instead. */
  export type Outbound =
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$Outbound;
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseToJSON(
  postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse:
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse,
): string {
  return JSON.stringify(
    PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$outboundSchema
      .parse(
        postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse,
      ),
  );
}

export function postOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostOrderPaymentsV3Track1a46dc7091f948928e250bb5205b69c7VoidResponse' from JSON`,
  );
}
