/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PutClientApiSettingsV1Data = {
  clientId?: string | undefined;
  createdAt?: Date | undefined;
  token?: string | undefined;
  updatedAt?: Date | undefined;
  webhookSecret?: string | undefined;
};

/**
 * 200
 */
export type PutClientApiSettingsV1ResponseBody = {
  data?: PutClientApiSettingsV1Data | undefined;
  status?: models.Status | undefined;
};

export type PutClientApiSettingsV1Response = {
  headers: { [k: string]: Array<string> };
  result: PutClientApiSettingsV1ResponseBody;
};

/** @internal */
export const PutClientApiSettingsV1Data$inboundSchema: z.ZodType<
  PutClientApiSettingsV1Data,
  z.ZodTypeDef,
  unknown
> = z.object({
  client_id: z.string().optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  token: z.string().optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  webhook_secret: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "client_id": "clientId",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "webhook_secret": "webhookSecret",
  });
});

/** @internal */
export type PutClientApiSettingsV1Data$Outbound = {
  client_id?: string | undefined;
  created_at?: string | undefined;
  token?: string | undefined;
  updated_at?: string | undefined;
  webhook_secret?: string | undefined;
};

/** @internal */
export const PutClientApiSettingsV1Data$outboundSchema: z.ZodType<
  PutClientApiSettingsV1Data$Outbound,
  z.ZodTypeDef,
  PutClientApiSettingsV1Data
> = z.object({
  clientId: z.string().optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  token: z.string().optional(),
  updatedAt: z.date().transform(v => v.toISOString()).optional(),
  webhookSecret: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    clientId: "client_id",
    createdAt: "created_at",
    updatedAt: "updated_at",
    webhookSecret: "webhook_secret",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutClientApiSettingsV1Data$ {
  /** @deprecated use `PutClientApiSettingsV1Data$inboundSchema` instead. */
  export const inboundSchema = PutClientApiSettingsV1Data$inboundSchema;
  /** @deprecated use `PutClientApiSettingsV1Data$outboundSchema` instead. */
  export const outboundSchema = PutClientApiSettingsV1Data$outboundSchema;
  /** @deprecated use `PutClientApiSettingsV1Data$Outbound` instead. */
  export type Outbound = PutClientApiSettingsV1Data$Outbound;
}

export function putClientApiSettingsV1DataToJSON(
  putClientApiSettingsV1Data: PutClientApiSettingsV1Data,
): string {
  return JSON.stringify(
    PutClientApiSettingsV1Data$outboundSchema.parse(putClientApiSettingsV1Data),
  );
}

export function putClientApiSettingsV1DataFromJSON(
  jsonString: string,
): SafeParseResult<PutClientApiSettingsV1Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutClientApiSettingsV1Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutClientApiSettingsV1Data' from JSON`,
  );
}

/** @internal */
export const PutClientApiSettingsV1ResponseBody$inboundSchema: z.ZodType<
  PutClientApiSettingsV1ResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => PutClientApiSettingsV1Data$inboundSchema).optional(),
  status: models.Status$inboundSchema.optional(),
});

/** @internal */
export type PutClientApiSettingsV1ResponseBody$Outbound = {
  data?: PutClientApiSettingsV1Data$Outbound | undefined;
  status?: models.Status$Outbound | undefined;
};

/** @internal */
export const PutClientApiSettingsV1ResponseBody$outboundSchema: z.ZodType<
  PutClientApiSettingsV1ResponseBody$Outbound,
  z.ZodTypeDef,
  PutClientApiSettingsV1ResponseBody
> = z.object({
  data: z.lazy(() => PutClientApiSettingsV1Data$outboundSchema).optional(),
  status: models.Status$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutClientApiSettingsV1ResponseBody$ {
  /** @deprecated use `PutClientApiSettingsV1ResponseBody$inboundSchema` instead. */
  export const inboundSchema = PutClientApiSettingsV1ResponseBody$inboundSchema;
  /** @deprecated use `PutClientApiSettingsV1ResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PutClientApiSettingsV1ResponseBody$outboundSchema;
  /** @deprecated use `PutClientApiSettingsV1ResponseBody$Outbound` instead. */
  export type Outbound = PutClientApiSettingsV1ResponseBody$Outbound;
}

export function putClientApiSettingsV1ResponseBodyToJSON(
  putClientApiSettingsV1ResponseBody: PutClientApiSettingsV1ResponseBody,
): string {
  return JSON.stringify(
    PutClientApiSettingsV1ResponseBody$outboundSchema.parse(
      putClientApiSettingsV1ResponseBody,
    ),
  );
}

export function putClientApiSettingsV1ResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PutClientApiSettingsV1ResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PutClientApiSettingsV1ResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutClientApiSettingsV1ResponseBody' from JSON`,
  );
}

/** @internal */
export const PutClientApiSettingsV1Response$inboundSchema: z.ZodType<
  PutClientApiSettingsV1Response,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.lazy(() => PutClientApiSettingsV1ResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type PutClientApiSettingsV1Response$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: PutClientApiSettingsV1ResponseBody$Outbound;
};

/** @internal */
export const PutClientApiSettingsV1Response$outboundSchema: z.ZodType<
  PutClientApiSettingsV1Response$Outbound,
  z.ZodTypeDef,
  PutClientApiSettingsV1Response
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.lazy(() => PutClientApiSettingsV1ResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutClientApiSettingsV1Response$ {
  /** @deprecated use `PutClientApiSettingsV1Response$inboundSchema` instead. */
  export const inboundSchema = PutClientApiSettingsV1Response$inboundSchema;
  /** @deprecated use `PutClientApiSettingsV1Response$outboundSchema` instead. */
  export const outboundSchema = PutClientApiSettingsV1Response$outboundSchema;
  /** @deprecated use `PutClientApiSettingsV1Response$Outbound` instead. */
  export type Outbound = PutClientApiSettingsV1Response$Outbound;
}

export function putClientApiSettingsV1ResponseToJSON(
  putClientApiSettingsV1Response: PutClientApiSettingsV1Response,
): string {
  return JSON.stringify(
    PutClientApiSettingsV1Response$outboundSchema.parse(
      putClientApiSettingsV1Response,
    ),
  );
}

export function putClientApiSettingsV1ResponseFromJSON(
  jsonString: string,
): SafeParseResult<PutClientApiSettingsV1Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutClientApiSettingsV1Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutClientApiSettingsV1Response' from JSON`,
  );
}
